package com.bidr.admin.dao.schema;

import com.bidr.admin.dao.entity.SysPortalColumn;
import com.bidr.kernel.mybatis.repository.BaseMybatisSchema;
import org.springframework.stereotype.Service;

/**
 * Title: SysPortalColumnSchema
 * @author Sharp
 * @since 2025/11/28
 */
@Service
public class SysPortalColumnSchema extends BaseMybatisSchema<SysPortalColumn> {
    static {
        setCreateDDL("CREATE TABLE IF NOT EXISTS `sys_portal_column` (\n" +
                "  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',\n" +
                "  `role_id` bigint(20) NOT NULL COMMENT '对应角色id',\n" +
                "  `portal_id` bigint(20) NOT NULL COMMENT '表id',\n" +
                "  `property` varchar(50) NOT NULL DEFAULT '' COMMENT '属性名',\n" +
                "  `db_field` varchar(50) NOT NULL DEFAULT '' COMMENT '数据字段名',\n" +
                "  `display_name` varchar(50) NOT NULL DEFAULT '' COMMENT '显示名称',\n" +
                "  `field_type` varchar(2) NOT NULL DEFAULT '0' COMMENT '属性类型PORTAL_FIELD_DICT',\n" +
                "  `reference` varchar(50) DEFAULT NULL COMMENT '字典或者跳转地址',\n" +
                "  `entity_field` varchar(50) DEFAULT NULL COMMENT '相关实体字段',\n" +
                "  `entity_condition` json DEFAULT NULL COMMENT '查询实体关系',\n" +
                "  `display_order` int(11) NOT NULL DEFAULT '0' COMMENT '显示顺序',\n" +
                "  `align` varchar(20) DEFAULT 'center' COMMENT '对齐方式',\n" +
                "  `width` int(11) NOT NULL DEFAULT '140' COMMENT '宽度',\n" +
                "  `fixed` varchar(1) NOT NULL DEFAULT '0' COMMENT '是否固定',\n" +
                "  `tooltip` varchar(1) NOT NULL DEFAULT '0' COMMENT '是否显示tooltip',\n" +
                "  `enable` varchar(1) NOT NULL DEFAULT '1' COMMENT '是否有效',\n" +
                "  `show` varchar(1) NOT NULL DEFAULT '1' COMMENT '是否显示',\n" +
                "  `filter_able` varchar(1) NOT NULL DEFAULT '1' COMMENT '是否可做筛选项',\n" +
                "  `sort_able` varchar(1) NOT NULL DEFAULT '1' COMMENT '是否可做排序项',\n" +
                "  `summary_able` varchar(1) NOT NULL DEFAULT '0' COMMENT '是否汇总',\n" +
                "  `edit_able` varchar(1) NOT NULL DEFAULT '0' COMMENT '表格是否可以编辑',\n" +
                "  `display_group_name` varchar(50) DEFAULT NULL COMMENT '字段分组名称',\n" +
                "  `detail_show` varchar(1) NOT NULL DEFAULT '1' COMMENT '详情时是否显示',\n" +
                "  `detail_size` int(11) NOT NULL DEFAULT '1' COMMENT '详情弹框布局大小',\n" +
                "  `detail_padding` int(11) NOT NULL DEFAULT '0' COMMENT '详情布局显示后占位填充',\n" +
                "  `add_show` varchar(1) NOT NULL DEFAULT '1' COMMENT '添加时是否显示',\n" +
                "  `add_size` int(11) NOT NULL DEFAULT '1' COMMENT '新增弹框布局大小',\n" +
                "  `add_padding` int(11) NOT NULL DEFAULT '0' COMMENT '新增弹框布局显示后占位填充',\n" +
                "  `add_disabled` varchar(50) NOT NULL DEFAULT '0' COMMENT '新增弹框disable显示',\n" +
                "  `edit_show` varchar(1) NOT NULL DEFAULT '1' COMMENT '编辑框是否显示',\n" +
                "  `edit_size` int(11) NOT NULL DEFAULT '1' COMMENT '编辑弹框布局大小',\n" +
                "  `edit_padding` int(11) NOT NULL DEFAULT '0' COMMENT '编辑弹框布局显示后占位填充',\n" +
                "  `edit_disabled` varchar(50) NOT NULL DEFAULT '0' COMMENT '编辑弹框布局disable显示',\n" +
                "  `required` varchar(1) NOT NULL DEFAULT '0' COMMENT '是否必填',\n" +
                "  `min` decimal(20,6) DEFAULT NULL COMMENT '最小值(长度)',\n" +
                "  `max` decimal(20,6) DEFAULT NULL COMMENT '最大值(长度)',\n" +
                "  `default_value` varchar(200) DEFAULT NULL COMMENT '默认内容',\n" +
                "  `mobile_display_type` varchar(2) NOT NULL DEFAULT '0' COMMENT '移动端显示类型',\n" +
                "  PRIMARY KEY (`id`),\n" +
                "  UNIQUE KEY `role_id_portal_id_property` (`role_id`,`portal_id`,`property`),\n" +
                "  KEY `role_id` (`role_id`),\n" +
                "  KEY `portal_id` (`portal_id`)\n" +
                ") COMMENT='系统表表头';");

        // 初始化Portal列配置数据 - AcUser(用户信息表)
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(1, 0, 1, 'userId', '', '用户ID', '3', NULL, NULL, NULL, 1, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(2, 0, 1, 'customerNumber', '', '用户编码', '1', NULL, NULL, NULL, 2, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(3, 0, 1, 'name', '', '用户姓名', '1', NULL, NULL, NULL, 5, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '账号信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(4, 0, 1, 'deptId', '', '部门ID', '1', NULL, NULL, NULL, 3, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(5, 0, 1, 'deptName', 'deptId', '部门名称', '11', 'AcDept', 'deptId', NULL, 7, 'center', 140, '0', '0', '1', '1', '1', '1', '1', '账号信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(6, 0, 1, 'userName', '', '用户账号', '1', NULL, NULL, NULL, 4, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '账号信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(7, 0, 1, 'nickName', '', '用户昵称', '1', NULL, NULL, NULL, 8, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '账号信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(8, 0, 1, 'email', '', '用户邮箱', '1', NULL, NULL, NULL, 9, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '账号信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(9, 0, 1, 'phoneNumber', '', '手机号码', '1', NULL, NULL, NULL, 10, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '账号信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(10, 0, 1, 'sex', '', '用户性别', '4', 'GENDER_DICT', NULL, NULL, 11, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '账号信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(11, 0, 1, 'avatar', '', '头像地址', '12', NULL, NULL, NULL, 6, 'center', 140, '0', '0', '1', '0', '1', '1', '0', '账号信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(12, 0, 1, 'passwordErrorTime', '', '密码输入错误次数', '3', NULL, NULL, NULL, 13, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '登录信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(13, 0, 1, 'passwordLastTime', '', '上次密码修改时间', '6', NULL, NULL, NULL, 14, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '登录信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(14, 0, 1, 'status', '', '帐号状态', '4', 'ACTIVE_STATUS_DICT', NULL, NULL, 12, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '账号信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(15, 0, 1, 'loginIp', '', '最后登录IP', '1', NULL, NULL, NULL, 15, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '登录信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(16, 0, 1, 'loginDate', '', '最后登录时间', '6', NULL, NULL, NULL, 16, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '登录信息', '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(17, 0, 1, 'remark', '', '备注', '10', NULL, NULL, NULL, 17, 'center', 140, '0', '0', '1', '1', '1', '1', '0', '账号信息', '1', 2, 0, '1', 2, 0, '0', '1', 2, 0, '0', '0', NULL, NULL, NULL);");

        // 初始化Portal列配置数据 - AcDept(部门表)
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(18, 0, 2, 'deptId', '', '部门id', '1', NULL, NULL, NULL, 0, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(19, 0, 2, 'pid', '', '父部门id', '1', NULL, NULL, NULL, 1, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(20, 0, 2, 'grandId', '', '祖父id', '1', NULL, NULL, NULL, 2, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(21, 0, 2, 'name', '', '部门名称', '1', NULL, NULL, NULL, 3, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(22, 0, 2, 'abbreviate', '', '简称', '1', NULL, NULL, NULL, 4, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(23, 0, 2, 'foundedTime', '', '建立时间', '6', NULL, NULL, NULL, 5, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(24, 0, 2, 'category', '', '类别', '1', NULL, NULL, NULL, 6, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(25, 0, 2, 'type', '', '类型', '1', NULL, NULL, NULL, 7, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(26, 0, 2, 'function', '', '职能', '1', NULL, NULL, NULL, 8, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(27, 0, 2, 'leader', '', '负责人', '1', NULL, NULL, NULL, 9, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(28, 0, 2, 'contact', '', '联系电话', '1', NULL, NULL, NULL, 10, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(29, 0, 2, 'address', '', '地址', '1', NULL, NULL, NULL, 11, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(30, 0, 2, 'status', '', '部门状态', '4', 'ACTIVE_STATUS_DICT', NULL, NULL, 12, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(31, 0, 2, 'showOrder', '', '显示顺序', '3', NULL, NULL, NULL, 13, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");

        // 初始化Portal列配置数据 - SaObjectStorage(对象存储记录)
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(32, 0, 3, 'id', '', 'id', '3', NULL, NULL, NULL, 0, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(33, 0, 3, 'name', '', '文件名', '1', NULL, NULL, NULL, 1, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(34, 0, 3, 'uri', '', '地址', '1', NULL, NULL, NULL, 2, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(35, 0, 3, 'size', '', '文件大小', '3', NULL, NULL, NULL, 3, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(36, 0, 3, 'type', '', '文件存储类型OSS_TYPE_DICT', '1', NULL, NULL, NULL, 4, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(37, 0, 3, 'createAt', '', '创建时间', '6', NULL, NULL, NULL, 5, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(38, 0, 3, 'updateAt', '', '更新时间', '6', NULL, NULL, NULL, 6, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");

        // 初始化Portal列配置数据 - SysConfig(参数配置表)
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(39, 0, 4, 'configId', '', '参数主键', '3', NULL, NULL, NULL, 1, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(40, 0, 4, 'configName', '', '参数名称', '1', NULL, NULL, NULL, 2, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(41, 0, 4, 'configKey', '', '参数键名', '1', NULL, NULL, NULL, 3, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(42, 0, 4, 'configValue', '', '参数键值', '1', NULL, NULL, NULL, 4, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(43, 0, 4, 'configType', '', '系统内置', '1', NULL, NULL, NULL, 5, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(44, 0, 4, 'createBy', '', '创建者', '3', NULL, NULL, NULL, 7, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(45, 0, 4, 'createTime', '', '创建时间', '6', NULL, NULL, NULL, 8, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(46, 0, 4, 'updateBy', '', '更新者', '3', NULL, NULL, NULL, 9, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(47, 0, 4, 'updateTime', '', '更新时间', '6', NULL, NULL, NULL, 10, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(48, 0, 4, 'remark', '', '备注', '10', NULL, NULL, NULL, 6, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");

        // 初始化Portal列配置数据 - SysDict(字典数据表)
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(49, 0, 5, 'dictId', '', '字典编码', '1', NULL, NULL, NULL, 2, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(50, 0, 5, 'dictPid', '', '字典父节点', '1', NULL, NULL, NULL, 8, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(51, 0, 5, 'dictSort', '', '字典排序', '3', NULL, NULL, NULL, 6, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(52, 0, 5, 'dictName', '', '字典类型', '1', NULL, NULL, NULL, 1, 'center', 140, '0', '0', '0', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(53, 0, 5, 'dictTitle', '', '字典显示名称', '1', NULL, NULL, NULL, 3, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(54, 0, 5, 'dictItem', '', '字典项名称', '1', NULL, NULL, NULL, 4, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(55, 0, 5, 'dictValue', '', '字典键值', '1', NULL, NULL, NULL, 7, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(56, 0, 5, 'dictLabel', '', '字典标签', '1', NULL, NULL, NULL, 5, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(57, 0, 5, 'isDefault', '', '是否默认', '4', 'BOOLEAN_DICT', NULL, NULL, 9, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(58, 0, 5, 'status', '', '状态', '4', 'BOOLEAN_DICT', NULL, NULL, 10, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(59, 0, 5, 'show', '', '是否显示', '4', 'BOOLEAN_DICT', NULL, NULL, 11, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(60, 0, 5, 'readOnly', '', '只读', '4', 'BOOLEAN_DICT', NULL, NULL, 12, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '0', 1, 0, '0', '0', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(61, 0, 5, 'createBy', '', '创建者', '3', NULL, NULL, NULL, 13, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(62, 0, 5, 'createTime', '', '创建时间', '6', NULL, NULL, NULL, 14, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(63, 0, 5, 'updateBy', '', '更新者', '3', NULL, NULL, NULL, 15, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(64, 0, 5, 'updateTime', '', '更新时间', '6', NULL, NULL, NULL, 16, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(65, 0, 5, 'remark', '', '备注', '1', NULL, NULL, NULL, 17, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");

        // 初始化Portal列配置数据 - SysDictType(字典类型表)
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(66, 0, 6, 'dictName', '', '字典类型', '1', NULL, NULL, NULL, 0, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(67, 0, 6, 'dictTitle', '', '字典显示名称', '1', NULL, NULL, NULL, 1, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(68, 0, 6, 'readOnly', '', '只读', '1', NULL, NULL, NULL, 2, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
        setInitData("INSERT INTO `sys_portal_column` (`id`, `role_id`, `portal_id`, `property`, `db_field`, `display_name`, `field_type`, `reference`, `entity_field`, `entity_condition`, `display_order`, `align`, `width`, `fixed`, `tooltip`, `enable`, `show`, `filter_able`, `sort_able`, `edit_able`, `display_group_name`, `detail_show`, `detail_size`, `detail_padding`, `add_show`, `add_size`, `add_padding`, `add_disabled`, `edit_show`, `edit_size`, `edit_padding`, `edit_disabled`, `required`, `min`, `max`, `default_value`) VALUES " +
                "(69, 0, 6, 'expired', '', '更新时间', '3', NULL, NULL, NULL, 3, 'center', 140, '0', '0', '1', '1', '1', '1', '0', NULL, '1', 1, 0, '1', 1, 0, '0', '1', 1, 0, '0', '0', NULL, NULL, NULL);");
    }
}
